### PR TITLE
Revision - Pass useful arguments for custom attributes

### PR DESCRIPTION
**Pull request by caseynix**
- Grabbing the functionality changes from PR #3

Adds the `$form_fields` parameter to the `wivm_create_update_user` action, allowing for the ability to add custom field values to the user meta data.

Adds the user ID to the `wivm_search_and_replace_text` filter, allowing for the ability to query custom user metadata and add these fields as replacement tokens.

### CODE REVIEW

**Comment by marcDeSantis** [comment]
Looks great. Sorry about the line endings. I will correct that going forward.

**Comment by jg314** [comment]
@marcDeSantis, I've adjusted the code to check if the user object exists first, since it was throwing an error in some cases. Now instead of passing the user ID, we're passing the entire object including the ID and some user meta information. Does this still work for your use case?

**Comment by marcDeSantis** [comment]
Yea - I can work with this. Thanks

**Comment by jg314** [comment]
@marcDeSantis, this pull request has been pushed to the WordPress repository as version 1.0.4. Thanks so much for helping us make the plugin better!

**Pull request merged**
