### PR TITLE
Modifications

### PR DESCRIPTION
**Pull request by bp-mrogers**

### CODE REVIEW

**Comment by jg314** [comment]
Thanks a ton for submitting the pull request. It's always great to have folks from the community contribute to our plugins. It would be great if you could do two things to make it easier for us to review the changes:

1. Add a description to your pull request outlining the purpose of your changes and how they benefit the plugin's users.
2. Update your pull request to match the spacing used on the existing plugin. If you look at the file changes  for the pull request it's hard to see what you changed since there are so many spacing adjustments.

Thanks again for contributing. We really appreciate it.

**Comment by bp-mrogers** [comment]
Thank you for the feedback. The PR was intended for a forked copy of the plugin rather than the wiredimpact:master branch which is why the description was brief. I made a simple modification to separate events of fixed time opportunities by repurposing the fixed opportunity checkbox. That way I can separate two types of fixed time opportunities into different widgets. I have closed the PR accordingly and you can disregard. I am enjoying using the plugin so far. Thanks!

**Comment by jg314** [comment]
Sounds good. Thanks for letting me know. I'm not sure exactly how you're modifying the plugin, but it's worth mentioning that you should be able to modify the checkbox using the template system included in the plugin. I'm always weary to recommend modifying the core plugin since that either means you can't update it in the future or any future updates will wipe out your changes.

**Comment by bp-mrogers** [comment]
I absolutely agree that modifying the core is less than desirable, but necessary in this case. That was part of the impetus for forking the repo, so that I can more easily merge conflicts when changes are pushed 
pushed to your master branch. Thanks again!

**Comment by jg314** [comment]
That makes total sense. Thanks for clarifying and good luck!

**Pull request closed without merging**
