### PR TITLE
Pass useful arguments for custom attributes

### PR DESCRIPTION
**Pull request by marcDeSantis**
Adds the `$formFields` parameter to the `wivm_create_update_user` action, allowing for the ability to add custom field values to the user meta data.

Adds the user ID to the `wivm_search_and_replace_text` filter, allowing for the ability to query custom user metadata and add these fields as replacement tokens.

### CODE REVIEW

**Comment by caseynix** [comment]
Hi @marcDeSantis - Could you clarify this added functionality for us maybe with a brief use case scenario and/or how it could be used. We're just trying to get a better understanding of where you're going with it.

In addition, the line ending changes you made. Did you make those or is your text editor set to unix and just changed them on save? The line endings that are set are specific for SVN as Subversion is very finicky about line endings.

**Comment by marcDeSantis** [comment]
The use case is for storing additional fields that are tied to the user. In my example, I want to store fields like t-shirt size, age and zip code with the user information. I've added these fields to the RSVP form via an action hook and now I want to save them as user metadata. Passing the formFields allows the function called by the `wivm_create_update_user` action to have access to these variables. 

I modified the `wivm_search_and_replace_text` action to be able to send these custom user fields out in the email to the Administrator when a new RSVP comes in.

> In addition, the line ending changes you made. Did you make those or is your text editor set to unix and just changed them on save?

I tried to fix those before creating the pull request, since I know it's terribly ugly. I am using the Atom IDE on a Mac. I tried modifying the line endings a few different ways, but it didn't seem to help. What operating system and editor do you guys use?

**Comment by caseynix** [comment]
Hi @marcDeSantis -

We've talked this over and like this change. However, the line endings we'll have to work around. Like I mentioned, we have them formatted to work on both Mac and Windows where SVN doesn't balk at us. We all use Sublime Text 3 with the setting of 'system' (whatever the OS uses).

So what we're going to do is create a new PR with just your functionality change (without all the LE changes) and work that in.

**Comment by caseynix** [comment]
@marcDeSantis Check out PR #7 to see if that has all your changes in there. Just want to be sure everything is there since there was so many eol changes in the diff.

**Comment by marcDeSantis** [comment]
Looks great. Thanks!

I will close this PR.

**Pull request closed without merging**
